### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by tamis-laan** [gosbd/gosbd#4] opened 2024-04-30 18:13 UTC
```
[transformer] 2024/04/30 18:02:22 msg: Ampere
[transformer] 2024/04/30 18:02:22 msg: Anarchism
[transformer] 2024/04/30 18:02:23 msg: Algorithm
[transformer] 2024/04/30 18:02:23 msg: Annual plant
[transformer] 2024/04/30 18:02:23 msg: Anthophyta
[transformer] 2024/04/30 18:02:23 msg: Albedo
[transformer] 2024/04/30 18:02:23 msg: A
[transformer] 2024/04/30 18:02:23 msg: Mouthwash
[transformer] 2024/04/30 18:02:23 msg: Alabama
[transformer] 2024/04/30 18:02:24 msg: Alexander the Great
[transformer] 2024/04/30 18:02:24 msg: Alfred Korzybski
[transformer] panic: runtime error: slice bounds out of range [:448] with length 447
[transformer]
[transformer] goroutine 22 [running]:
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).sentenceBoundaryPunctuation(0xc000140460, {0xc001e7c700?, 0x1c0?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.1/internal/processor/processor.go:180 +0x2a5
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).processText(0xc000140460, {0xc0022c6000, 0x1bd})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.1/internal/processor/processor.go:148 +0x23c
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).checkForPunctuation(0xc000140460, {0xc0022c6000, 0x1bd})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.1/internal/processor/processor.go:130 +0x91
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).splitIntoSegments(0xc000140460, {0xc0022a0800?, 0x275f?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.1/internal/processor/processor.go:57 +0x2ff
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).Process(0xc000140460, {0xc0012c7000?, 0xc000092aa0?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.1/internal/processor/processor.go:43 +0x2a5
[transformer] github.com/gosbd/gosbd/internal/segmenter.(*Segmenter).Segment(0xc000119170, {0xc0012c7000?, 0x280d?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.1/internal/segmenter/segmenter.go:37 +0x5d
[transformer] main.main.func1({0x872b38, 0xc001f80100})
[transformer] 	/app/cmd/transformer/main.go:62 +0x96
[transformer] github.com/nats-io/nats.go/jetstream.(*pullConsumer).Consume.func1(0xc000144d20)
[transformer] 	/go/pkg/mod/github.com/nats-io/nats.go@v1.34.1/jetstream/pull.go:245 +0x2be
[transformer] github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc00021a708, 0xc0001560e0)
[transformer] 	/go/pkg/mod/github.com/nats-io/nats.go@v1.34.1/nats.go:3106 +0x412
[transformer] created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked in goroutine 1
[transformer] 	/go/pkg/mod/github.com/nats-io/nats.go@v1.34.1/nats.go:4320 +0x3a8
```
`sentences := segmenter.Segment(schema.Content)`

There seems to be a problem with the module. It fails on the rendered wikitext (plaintext) from https://en.wikipedia.org/wiki/Alfred_Korzybski.

**Comment by sri-shubham** [comment] 2024-05-01 12:19
Hi I would like to fix this, can you assign it to me?

**Comment by yohamta** [comment] 2024-05-01 12:48
@sri-shubham Thanks a lot!

**Comment by sri-shubham** [comment] 2024-05-02 07:25
@yohamta I have added a fix with test

**Comment by yohamta** [comment] 2024-05-02 07:33
@sri-shubham @tamis-laan Thanks a lot!

**Comment by tamis-laan** [comment] 2024-05-03 09:12
```
[transformer] 2024/05/03 09:11:24 Trace 1
[transformer] 2024/05/03 09:11:24 ./config.yaml not found
[transformer] 2024/05/03 09:11:24 HELLO WORLD
[transformer] 2024/05/03 09:11:25 Anarchism
[transformer] 2024/05/03 09:11:25 Albedo
[transformer] 2024/05/03 09:11:25 A
[transformer] 2024/05/03 09:11:25 Alabama
[transformer] 2024/05/03 09:11:26 Ababda people
[transformer] 2024/05/03 09:11:26 Achilles
[transformer] 2024/05/03 09:11:27 Abraham Lincoln
[transformer] 2024/05/03 09:11:27 Aristotle
[transformer] 2024/05/03 09:11:28 An American in Paris
[transformer] 2024/05/03 09:11:28 Academy Award for Best Production Design
[transformer] panic: runtime error: slice bounds out of range [:287] with length 260
[transformer]
[transformer] goroutine 22 [running]:
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).sentenceBoundaryPunctuation(0xc000140460, {0xc001682000?, 0x122?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.2/internal/processor/processor.go:175 +0x2b5
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).processText(0xc000140460, {0xc00037e5a0, 0x120})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.2/internal/processor/processor.go:146 +0x23c
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).checkForPunctuation(0xc000140460, {0xc00037e5a0, 0x120})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.2/internal/processor/processor.go:128 +0x91
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).splitIntoSegments(0xc000140460, {0xc001572000?, 0x1ef49?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.2/internal/processor/processor.go:57 +0x2ea
[transformer] github.com/gosbd/gosbd/internal/processor.(*Processor).Process(0xc000140460, {0xc002056000?, 0xc002380008?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.2/internal/processor/processor.go:43 +0x2a5
[transformer] github.com/gosbd/gosbd/internal/segmenter.(*Segmenter).Segment(0xc000119170, {0xc002056000?, 0x2?})
[transformer] 	/go/pkg/mod/github.com/gosbd/gosbd@v0.1.2/internal/segmenter/segmenter.go:37 +0x5d
[transformer] main.main.func1({0x872af8, 0xc001c30580})
[transformer] 	/app/cmd/transformer/main.go:63 +0x10b
[transformer] github.com/nats-io/nats.go/jetstream.(*pullConsumer).Consume.func1(0xc0002a82a0)
[transformer] 	/go/pkg/mod/github.com/nats-io/nats.go@v1.34.1/jetstream/pull.go:245 +0x2be
[transformer] github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc00021a708, 0xc0001560e0)
[transformer] 	/go/pkg/mod/github.com/nats-io/nats.go@v1.34.1/nats.go:3106 +0x412
[transformer] created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked in goroutine 1
[transformer] 	/go/pkg/mod/github.com/nats-io/nats.go@v1.34.1/nats.go:4320 +0x3a8
```

Nope now it crashes on `Academy Award for Best Production Design` i.e. https://en.wikipedia.org/wiki/Academy_Award_for_Best_Production_Design

**Comment by sri-shubham** [comment] 2024-05-03 09:43
I am a bit busy today I can look at it tomorrow

**Comment by yohamta** [comment] 2024-05-03 09:46
I've just added a test here, but couldn't reproduce the panic. @sri-shubham Could you pls share the exact input text?

https://github.com/gosbd/gosbd/blob/2ee0571a7d32f440316e17dc5e4e160764479db2/internal/lang/english_test.go#L438-L453

**Comment by sri-shubham** [comment] 2024-05-03 09:51
> I've just added a test here, but couldn't reproduce the panic. @sri-shubham Could you pls share the exact input text?

I think you want to tag @tamis-laan?

**Comment by yohamta** [comment] 2024-05-03 09:53
oh right, my bad.

**Comment by sri-shubham** [comment] 2024-05-04 05:36
I cannot reproduce it at my end. @tamis-laan can you share a small example that can reproduce this issue?

**Comment by tamis-laan** [comment] 2024-05-04 08:24
@sri-shubham 
Because `segmenter.Segment(schema.Content)` doesn't return an error I can't intercept and dump the wikitext do disk.

**Comment by yohamta** [comment] 2024-05-05 04:56
@tamis-laan Hey, can you please clarify a bit more context where you are facing the problem? I thought you could take the `schema.Content` to be dumped in your code you've mentioned.

**Comment by sri-shubham** [comment] 2024-05-06 08:39
@tamis-laan you can even give me this and replace your raw input text as well. That should be enough if it reproduces the issue

```
package main

import (
    "fmt"
    "github.com/gosbd/gosbd"
)

// This example segments a text string into individual sentences.
func main() {
    segmenter := gosbd.NewSegmenter("en")
    text := "This is a sentence. And this is another one."
    sentences := segmenter.Segment(text)
    for _, sentence := range sentences {
        fmt.Println(sentence)
    }
}
```

**Comment by yohamta** [comment] 2024-05-14 08:41
Since it's not reproducing any more, please let me close the issue. Thanks for solving the problem, @sri-shubham.

**Closed by yohamta** 2024-05-14 08:41 UTC
Labels: bug, good first issue

**Comment by yohamta** [comment] 2024-05-14 16:08
Okay, let us know how to reproduce it when you have a chance. Thanks again for reporting the issue.
